FROM ubuntu:latest
LABEL authors="evgeniy"

RUN apt-get update
RUN apt-get install -y curl zip unzip
RUN apt-get clean

# Install SDKMAN
RUN curl -s "https://get.sdkman.io" | bash

# Source SDKMAN and install the latest OpenJDK
RUN bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install java 22-open"

ENV JAVA_HOME="/root/.sdkman/candidates/java/current"

ENV PATH="${PATH}:${JAVA_HOME}/bin"
RUN echo $PATH

CMD ["java", "--version"]