services:

  gym-manager:
    container_name: gym-manager-app
    env_file:
      - env.dev
    build:
      context: ./backend
      args:
        DOCKER_HUB_ID: ${DOCKER_HUB_ID}
    image: ${DOCKER_HUB_ID}/gym-manager
    volumes:
      - ./backend/target:/app
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - gym-manager-network

  bot:
    container_name: bot-app
    env_file:
      - env.dev
    build:
      context: ../tstream-bot
      args:
        DOCKER_HUB_ID: ${DOCKER_HUB_ID}
    image: ${DOCKER_HUB_ID}/bot
    volumes:
      - ../tstream-bot/target:/app
    depends_on:
      - gym-manager
    networks:
      - gym-manager-network

  nginx:
    image: nginx:1.27.1-alpine
    ports:
      - "80:80"
    depends_on:
      - gym-manager
      - bot
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - gym-manager-network

  mysql-db:
    container_name: mysql-db-app
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 6s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - gym-manager-network

volumes:
    mysql-data:
      external: true
networks:
  gym-manager-network:
