services:
  gym-manager:
    container_name: ts-gym-manager
    image: ts-gym-manager:1.0.5
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ts-network

  tg-bot:
    container_name: ts-telegram-bot
    image: ts-telegram-bot:1.0.5
    env_file:
      - .env
    depends_on:
      - gym-manager
    networks:
      - ts-network

  nginx:
    container_name: nginx
    image: nginx:1.27.1-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gym-manager
      - tg-bot
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/tstream.com.ua/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/tstream.com.ua/privkey.pem:/etc/nginx/certs/privkey.pem
    networks:
      - ts-network

  mysql:
    container_name: mysql
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 15s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ts-network

volumes:
  mysql-data:
    external: false
networks:
  ts-network: